name: CI Leitor Zen

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Instalar dependências
        run: npm ci

      - name: Instalar navegadores do Playwright
        run: npx playwright install --with-deps chromium

      - name: Construir a extensão
        run: npm run build

      - name: Rodar testes E2E com Playwright
        run: npm run test:e2e

      - name: Publicar relatório de testes
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7

      - name: Publicar pacote da extensão
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: leitor-zen-package
          path: dist/leitor-zen.zip
          retention-days: 30